#!/bin/sh

get_config() {
    . "/etc/setup.conf"

    dev_bin_dir="bin"
    dev_lib_dir="lib"
    dev_share_dir="share"
    # dev_init_dir should be system dependent and specified in setup.conf
    dev_etc_dir="etc"
}

get_config
