#!/bin/sh

get_config() {
    while IFS='=' read key value; do
        if [ "$key" = "bin_dirs" ]; then
            dev_bin_dir="${value%:*}"
            sys_bin_dir="${value#*:}"
        elif [ "$key" = "lib_dirs" ]; then
            dev_lib_dir="${value%:*}"
            sys_lib_dir="${value#*:}"
        elif [ "$key" = "share_dirs" ]; then
            dev_share_dir="${value%:*}"
            sys_share_dir="${value#*:}"
        elif [ "$key" = "init_dirs" ]; then
            dev_init_dir="${value%:*}"
            sys_init_dir="${value#*:}"
        elif [ "$key" = "etc_dirs" ]; then
            dev_etc_dir="${value%:*}"
            sys_etc_dir="${value#*:}"
        fi
    done <"/etc/setup.conf"
}

get_config
