#!/bin/sh

get_config() {
    pkg_bin_dir="bin"
    pkg_lib_dir="lib"
    pkg_share_dir="share"
    # pkg_init_dir should be system dependent and specified in setup.conf
    pkg_etc_dir="etc"

    . "/etc/setup.conf"
}

get_config
